### ISSUE TITLE
Page reduction

### ISSUE THREAD

**Issue by Yer1k** [andrewkroening/orange-modeling-project#9]
Guys, we need to work on page reduction and "STATS" wording optimization, cuz this professional report **ACTUALLY targets "non-statistician"**.

![image](https://user-images.githubusercontent.com/81750079/204392457-39c2cd99-4816-48a8-9180-6642e417bb97.png)
(page 4 on Projectintro-1.pdf)

We can work on transform that after tomorrow's crazy dues, no big deal. @andrewkroening @echodpp 
@poojakabber7

**Comment by andrewkroening** [comment]
Thanks @Yer1k , it looks like we're good to go!
